springdoc:
  swagger-ui:
  path: /swagger-ui.html
  use-fqn: true
logging:
  file:
    path: ./log/was-log

spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 289a13264317080aeb3c1feb3d9d9d0e
            client-secret: obk2faFGMkbgfDSVqPQqp2TxhKGN5ESy
            client-name: kakao
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            scope: profile
            authorization_grant_type: authorization_code
            client-authentication-method: POST

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id

  redis:
    host: hyuki.app
    port: 16379
