spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://222.117.225.28:8081/korello?serverTimezone=UTC&characterEncoding=UTF-8
      driver-class-name: org.mariadb.jdbc.Driver
      username: root
      password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MariaDB10Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

  springdoc:
    swagger-ui:
    path: /swagger-ui.html
